
[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.26'        # <-- set this to EXACT version used in production
optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'        # BSC supports London/Shanghai; set to match deployed build
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 100
