[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']

# EXACT compiler version used in production
solc_version = '0.8.24'

# Optimizer settings (must match deploy/verification)
optimizer = true
optimizer_runs = 200

# EVM target used at deploy (оставляем как в билде)
evm_version = 'shanghai'

# Permissions for scripts that read local files
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 100
